#include <pitches.h>

// DEFINE ALL PINS
#define E4GREEN 5
#define F4YELLOW 6
#define G4RED 7
#define A4BLUE 8
#define B4GREEN 9
#define C5YELLOW 10
#define D5RED 11
#define E5BLUE 12
#define D4WHITE 13

int duration = 250; // TEMPO
// SET UP KEY FOR THE SONG
//                0       1           2       3         4       5         6       7       8       9
int melody[] = {NOTE_E4, NOTE_F4, NOTE_G4, NOTE_A4, NOTE_B4, NOTE_C5, NOTE_D5, NOTE_E5, NOTE_F5, NOTE_D4};
int pin = 4; // PIN FOR PASSIVE BUZZER 

void setup() {
  //put your setup code here, to run once:
  // SET ALL PINS TO OUTPUT
  pinMode(E4GREEN,OUTPUT);
  pinMode(F4YELLOW, OUTPUT);
  pinMode(G4RED, OUTPUT);
  pinMode(A4BLUE,OUTPUT);
  pinMode(B4GREEN, OUTPUT);
  pinMode(C5YELLOW, OUTPUT);
  pinMode(D5RED,OUTPUT);
  pinMode(E5BLUE, OUTPUT);
  pinMode(D4WHITE, OUTPUT);

  // TURN ON THE FIRST NOTE
  digitalWrite(F4YELLOW, HIGH);
  digitalWrite(E4GREEN, LOW);
  digitalWrite(G4RED, LOW);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(C5YELLOW, LOW);
  digitalWrite(D5RED, LOW);
  digitalWrite(E5BLUE, LOW);
  digitalWrite(D4WHITE, LOW);
}

void loop() {
  // put your main code here, to run repeatedly:
  digitalWrite(F4YELLOW, HIGH);
  tone(pin, melody[1], duration);
  delay(duration);
  digitalWrite(F4YELLOW, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration);
  delay(duration);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration*2);
  delay(duration*2);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(F4YELLOW, HIGH);
  tone(pin, melody[1], duration);
  delay(duration);
  digitalWrite(F4YELLOW, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration);
  delay(duration);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration*2);
  delay(duration*2);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(F4YELLOW, HIGH);
  tone(pin, melody[1], duration);
  delay(duration);
  digitalWrite(F4YELLOW, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration);
  delay(duration);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(E5BLUE, HIGH);
  tone(pin, melody[7], duration);
  delay(duration);
  digitalWrite(E5BLUE, LOW);
  digitalWrite(D5RED, HIGH);
  tone(pin, melody[6], duration*2);
  delay(duration*2);
  digitalWrite(D5RED, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(C5YELLOW, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);  // END FIRST 2 MEASURES
  digitalWrite(C5YELLOW, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration);
  delay(duration);
  digitalWrite(G4RED, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration*5);
  delay(duration*5);
  digitalWrite(E4GREEN, LOW);
  digitalWrite(D4WHITE, HIGH);
  tone(pin, melody[9], duration);
  delay(duration);
  digitalWrite(D4WHITE, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration);
  delay(duration);
  digitalWrite(E4GREEN, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration);
  delay(duration);
  digitalWrite(G4RED, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration*5);
  delay(duration*5);
  digitalWrite(E4GREEN, LOW);
  digitalWrite(F4YELLOW, HIGH);
  tone(pin, melody[1], duration);
  delay(duration);
  digitalWrite(F4YELLOW, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration);
  delay(duration);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration*2);
  delay(duration*2);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(F4YELLOW, HIGH);
  tone(pin, melody[1], duration);
  delay(duration);
  digitalWrite(F4YELLOW, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration);
  delay(duration);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration*2);
  delay(duration*2);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(F4YELLOW, HIGH);
  tone(pin, melody[1], duration);
  delay(duration);
  digitalWrite(F4YELLOW, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration);
  delay(duration);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(E5BLUE, HIGH);
  tone(pin, melody[7], duration);
  delay(duration);
  digitalWrite(E5BLUE, LOW);
  digitalWrite(D5RED, HIGH);
  tone(pin, melody[6], duration*2);
  delay(duration*2);
  digitalWrite(D5RED, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(C5YELLOW, HIGH);
  tone(pin, melody[4], duration);
  delay(duration); // END FIRST 2 MEASURES THE SECOND TIME
  digitalWrite(C5YELLOW, LOW);
  digitalWrite(E5BLUE, HIGH);
  tone(pin, melody[7], duration);
  delay(duration);
  digitalWrite(E5BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration*5);
  delay(duration*5);
  digitalWrite(G4RED, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration);
  delay(duration);
  digitalWrite(G4RED, LOW);
  digitalWrite(D4WHITE, HIGH);
  tone(pin, melody[9], duration);
  delay(duration);
  digitalWrite(D4WHITE, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration*3);
  delay(duration*3); // END FIRST VERSE
  digitalWrite(E4GREEN, LOW);
  digitalWrite(D4WHITE, HIGH);
  tone(pin, melody[9], duration);
  delay(duration);
  digitalWrite(D4WHITE, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration);
  delay(duration);
  digitalWrite(E4GREEN, LOW);
  digitalWrite(F4YELLOW, HIGH);
  tone(pin, melody[1], duration*2);
  delay(duration*2);
  digitalWrite(F4YELLOW, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration);
  delay(duration);
  digitalWrite(G4RED, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration);
  delay(duration);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration*2);
  delay(duration*2);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(C5YELLOW, HIGH);
  tone(pin, melody[5], duration);
  delay(duration);
  digitalWrite(C5YELLOW, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration*3);
  delay(duration*3); // END SECOND REPEATED PART
  digitalWrite(C5YELLOW, LOW);
  digitalWrite(E5BLUE, HIGH);
  tone(pin, melody[7], duration);
  delay(duration);
  digitalWrite(E5BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration*5);
  delay(duration*5);
  digitalWrite(G4RED, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration);
  delay(duration);
  digitalWrite(G4RED, LOW);
  digitalWrite(D4WHITE, HIGH);
  tone(pin, melody[9], duration);
  delay(duration);
  digitalWrite(D4WHITE, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration*3);
  delay(duration*3); // END FIRST VERSE
  digitalWrite(E4GREEN, LOW);
  digitalWrite(D4WHITE, HIGH);
  tone(pin, melody[9], duration);
  delay(duration);
  digitalWrite(D4WHITE, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration);
  delay(duration);
  digitalWrite(E4GREEN, LOW);
  digitalWrite(F4YELLOW, HIGH);
  tone(pin, melody[1], duration*2);
  delay(duration*2);
  digitalWrite(F4YELLOW, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration);
  delay(duration);
  digitalWrite(G4RED, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration);
  delay(duration);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration*2);
  delay(duration*2);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(C5YELLOW, HIGH);
  tone(pin, melody[5], duration);
  delay(duration);
  digitalWrite(C5YELLOW, LOW);
  digitalWrite(D5RED, HIGH);
  tone(pin, melody[6], duration);
  delay(duration);
  digitalWrite(D5RED, LOW);
  digitalWrite(E5BLUE, HIGH);
  tone(pin, melody[7], duration*3);
  delay(duration*3);
  digitalWrite(C5YELLOW, LOW);
  digitalWrite(E5BLUE, HIGH);
  tone(pin, melody[7], duration);
  delay(duration);
  digitalWrite(E5BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration*5);
  delay(duration*5);
  digitalWrite(G4RED, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration);
  delay(duration);
  digitalWrite(G4RED, LOW);
  digitalWrite(D4WHITE, HIGH);
  tone(pin, melody[9], duration);
  delay(duration);
  digitalWrite(D4WHITE, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration*3);
  delay(duration*3); // END FIRST VERSE
  digitalWrite(E4GREEN, LOW);
  digitalWrite(D4WHITE, HIGH);
  tone(pin, melody[9], duration);
  delay(duration);
  digitalWrite(D4WHITE, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration);
  delay(duration);
  digitalWrite(E4GREEN, LOW);
  digitalWrite(F4YELLOW, HIGH);
  tone(pin, melody[1], duration*2);
  delay(duration*2);
  digitalWrite(F4YELLOW, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration);
  delay(duration);
  digitalWrite(G4RED, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration);
  delay(duration);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration*2);
  delay(duration*2);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(C5YELLOW, HIGH);
  tone(pin, melody[5], duration);
  delay(duration);
  digitalWrite(C5YELLOW, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration*3);
  delay(duration*3); // END SECOND REPEATED PART
  digitalWrite(E4GREEN, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration);
  delay(duration);
  digitalWrite(E4GREEN, LOW);
  digitalWrite(D4WHITE, HIGH);
  tone(pin, melody[9], duration);
  delay(duration);
  digitalWrite(D4WHITE, LOW);
  digitalWrite(F4YELLOW, HIGH);
  tone(pin, melody[1], duration);
  delay(duration);
  digitalWrite(F4YELLOW, LOW);
  digitalWrite(E4GREEN, HIGH);
  tone(pin, melody[0], duration);
  delay(duration);
  digitalWrite(E4GREEN, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration);
  delay(duration);
  digitalWrite(G4RED, LOW);
  digitalWrite(F4YELLOW, HIGH);
  tone(pin, melody[1], duration);
  delay(duration);
  digitalWrite(F4YELLOW, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration);
  delay(duration);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(G4RED, HIGH);
  tone(pin, melody[2], duration);
  delay(duration);
  digitalWrite(G4RED, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration);
  delay(duration);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(C5YELLOW, HIGH);
  tone(pin, melody[5], duration);
  delay(duration);
  digitalWrite(C5YELLOW, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(D5RED, HIGH);
  tone(pin, melody[6], duration);
  delay(duration);
  digitalWrite(D5RED, LOW);
  digitalWrite(C5YELLOW, HIGH);
  tone(pin, melody[5], duration);
  delay(duration);
  digitalWrite(C5YELLOW, LOW);
  digitalWrite(E5BLUE, HIGH);
  tone(pin, melody[7], duration);
  delay(duration);
  digitalWrite(E5BLUE, LOW);
  digitalWrite(D5RED, HIGH);
  tone(pin, melody[6], duration);
  delay(duration);
  digitalWrite(D5RED, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration/2);
  delay(duration/2);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(C5YELLOW, HIGH);
  tone(pin, melody[5], duration/2 + duration);
  delay(duration);
  digitalWrite(C5YELLOW, LOW);
  digitalWrite(A4BLUE, HIGH);
  tone(pin, melody[3], duration/2);
  delay(duration/2);
  digitalWrite(A4BLUE, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration/2 + duration);
  delay(duration);
  digitalWrite(B4GREEN, LOW);
  digitalWrite(B4GREEN, HIGH);
  tone(pin, melody[4], duration*4);
  delay(duration*4);
  digitalWrite(B4GREEN, LOW);
  
}
